package com.agentmusic.agentmusic_backend.planner;

public enum PlanStepType {
    READ_USER_PREFERENCES,
    READ_CHAT_CONTEXT,
    READ_LOCAL_SESSION,
    READ_PLAYLIST_HISTORY,
    LOOKUP_TRACK,
    SEARCH_TRACKS,
    LOOKUP_ARTIST,
    GENERATE_RECOMMENDATION_CANDIDATES,
    RANK_RECOMMENDATION_CANDIDATES,
    CREATE_RECOMMENDATION_PLAYLIST,
    UPDATE_PLAYBACK_STATE,
    PERSIST_CHAT_REPLY
}
