CREATE DATABASE IF NOT EXISTS agentmusic
    DEFAULT CHARACTER SET utf8mb4
    DEFAULT COLLATE utf8mb4_0900_ai_ci;

USE agentmusic;

CREATE TABLE IF NOT EXISTS users (
    id CHAR(36) PRIMARY KEY COMMENT 'Application user UUID',
    username VARCHAR(50) NOT NULL,
    email VARCHAR(100) NOT NULL,
    password_hash VARCHAR(255) NULL,
    preferences JSON NOT NULL,
    created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    CONSTRAINT uk_users_username UNIQUE (username),
    CONSTRAINT uk_users_email UNIQUE (email)
) ENGINE = InnoDB COMMENT = 'Registered users and long-term recommendation preferences';

CREATE TABLE IF NOT EXISTS playlists (
    id CHAR(36) PRIMARY KEY COMMENT 'Playlist UUID',
    user_id CHAR(36) NOT NULL,
    name VARCHAR(100) NOT NULL,
    version INT NOT NULL,
    created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_playlists_user FOREIGN KEY (user_id) REFERENCES users (id) ON DELETE CASCADE,
    CONSTRAINT uk_playlists_user_version UNIQUE (user_id, version),
    INDEX idx_playlists_user_created_at (user_id, created_at DESC)
) ENGINE = InnoDB COMMENT = 'Historical recommendation playlists generated by the agent';

CREATE TABLE IF NOT EXISTS tracks (
    track_id VARCHAR(50) PRIMARY KEY COMMENT 'Spotify track id',
    title VARCHAR(200) NOT NULL,
    artist_id VARCHAR(50) NULL,
    album_name VARCHAR(200) NULL,
    album_id VARCHAR(50) NULL,
    duration_ms INT NULL,
    preview_url TEXT NULL,
    album_image_url TEXT NULL,
    updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    last_accessed_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    INDEX idx_tracks_last_accessed_at (last_accessed_at),
    INDEX idx_tracks_artist_id (artist_id),
    INDEX idx_tracks_album_id (album_id)
) ENGINE = InnoDB COMMENT = 'Cached track metadata fetched from Spotify';

CREATE TABLE IF NOT EXISTS playlist_tracks (
    id CHAR(36) PRIMARY KEY COMMENT 'Playlist track row UUID',
    playlist_id CHAR(36) NOT NULL,
    track_id VARCHAR(50) NOT NULL,
    position INT NOT NULL COMMENT 'Zero-based order index within playlist',
    added_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_playlist_tracks_playlist FOREIGN KEY (playlist_id) REFERENCES playlists (id) ON DELETE CASCADE,
    CONSTRAINT fk_playlist_tracks_track FOREIGN KEY (track_id) REFERENCES tracks (track_id),
    CONSTRAINT uk_playlist_tracks_playlist_position UNIQUE (playlist_id, position),
    CONSTRAINT uk_playlist_tracks_playlist_track UNIQUE (playlist_id, track_id),
    INDEX idx_playlist_tracks_track_id (track_id)
) ENGINE = InnoDB COMMENT = 'Many-to-many playlist and track relation with explicit ordering';

CREATE TABLE IF NOT EXISTS artists (
    artist_id VARCHAR(50) PRIMARY KEY COMMENT 'Spotify artist id',
    name VARCHAR(100) NOT NULL,
    bio TEXT NULL,
    image_url TEXT NULL,
    followers INT NULL,
    updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
) ENGINE = InnoDB COMMENT = 'Cached artist metadata';

CREATE TABLE IF NOT EXISTS chat_messages (
    id CHAR(36) PRIMARY KEY COMMENT 'Message UUID',
    user_id CHAR(36) NOT NULL,
    message TEXT NOT NULL,
    role VARCHAR(20) NOT NULL COMMENT 'USER or AGENT',
    metadata JSON NULL,
    created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_chat_messages_user FOREIGN KEY (user_id) REFERENCES users (id) ON DELETE CASCADE,
    INDEX idx_chat_messages_user_created_at (user_id, created_at DESC)
) ENGINE = InnoDB COMMENT = 'Persisted chat history between user and agent';

CREATE TABLE IF NOT EXISTS sessions (
    id CHAR(36) PRIMARY KEY COMMENT 'Session UUID',
    user_id CHAR(36) NOT NULL,
    current_track_id VARCHAR(50) NULL,
    current_position_ms INT NULL,
    is_playing BOOLEAN NOT NULL DEFAULT FALSE,
    playback_mode VARCHAR(20) NOT NULL DEFAULT 'SEQUENTIAL',
    device_id VARCHAR(100) NULL,
    last_updated DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    expires_at DATETIME NOT NULL,
    CONSTRAINT fk_sessions_user FOREIGN KEY (user_id) REFERENCES users (id) ON DELETE CASCADE,
    CONSTRAINT uk_sessions_user_device UNIQUE (user_id, device_id),
    INDEX idx_sessions_user_last_updated (user_id, last_updated DESC),
    INDEX idx_sessions_expires_at (expires_at)
) ENGINE = InnoDB COMMENT = 'Durable session snapshots for playback recovery and multi-device sync';
